const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });
const cloudinary = require('cloudinary').v2;
const mongoose = require('mongoose');
const Product = require('../models/productModel');

// 1. Configure Cloudinary
// (Assumes CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET are in .env)
cloudinary.config({
    cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
    api_key: process.env.CLOUDINARY_API_KEY,
    api_secret: process.env.CLOUDINARY_API_SECRET
});

const imagesToUpload = [
    '/Users/mac/.gemini/antigravity/brain/599d65ff-badf-477c-951a-f855010ea444/uploaded_image_0_1769550298415.jpg',
    '/Users/mac/.gemini/antigravity/brain/599d65ff-badf-477c-951a-f855010ea444/uploaded_image_1_1769550298415.jpg',
    '/Users/mac/.gemini/antigravity/brain/599d65ff-badf-477c-951a-f855010ea444/uploaded_image_2_1769550298415.jpg',
    '/Users/mac/.gemini/antigravity/brain/599d65ff-badf-477c-951a-f855010ea444/uploaded_image_3_1769550298415.jpg',
    '/Users/mac/.gemini/antigravity/brain/599d65ff-badf-477c-951a-f855010ea444/uploaded_image_4_1769550298415.jpg'
];

const uploadImage = async (path) => {
    try {
        const result = await cloudinary.uploader.upload(path, {
            folder: 'malaksit-products'
        });
        console.log(`Uploaded ${path} -> ${result.secure_url}`);
        return {
            publicId: result.public_id,
            url: result.secure_url,
            isMain: false // We'll set the first one to main later
        };
    } catch (error) {
        console.error(`Error uploading ${path}:`, error);
        return null;
    }
};

const run = async () => {
    try {
        // Connect to DB
        await mongoose.connect(process.env.MONGO_URI);
        console.log("MongoDB Connected");

        // Upload images
        const uploadedImages = [];
        for (const imgPath of imagesToUpload) {
            const imgData = await uploadImage(imgPath);
            if (imgData) uploadedImages.push(imgData);
        }

        if (uploadedImages.length > 0) {
            uploadedImages[0].isMain = true;
        }

        // Create Product
        const newProduct = new Product({
            title: "Elegant Winter Dress Collection",
            // Slug will be auto-generated by our controller update, 
            // BUT since we are using Mongoose directly, we might need to set it or rely on a pre-save hook. 
            // The controller changes don't affect Mongoose middleware unless we added it to schema.
            // We didn't add a pre-save hook, we added logic to the controller! 
            // So we must manually generate slug here.
            slug: "elegant-winter-dress-collection-" + Date.now(),
            description: "Beautiful warm dresses for the winter season. Available in Blue, Brown, Green, and Red.",
            price: 79.99,
            category: "girls-clothing",
            images: uploadedImages,
            // We can add colors if we want, but for now we'll keep it simple
            colors: []
        });

        await newProduct.save();
        console.log(`Product created with ID: ${newProduct._id}`);

    } catch (error) {
        console.error("Error:", error);
    } finally {
        await mongoose.disconnect();
        process.exit();
    }
};

run();
